# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
#all:

all:
  .settings:
    library-doctrine-listener:
      # Class to notify when a Library is saved;
      # extends Doctrine_Record_Listener
      class: LibrarySfGuardListener

