<?php


/**
 * This class adds structure of 'eresources' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Jul 21 11:41:56 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class EResourceMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.EResourceMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(EResourcePeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(EResourcePeer::TABLE_NAME);
		$tMap->setPhpName('EResource');
		$tMap->setClassname('EResource');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addColumn('ALT_ID', 'AltId', 'VARCHAR', false, 3);

		$tMap->addColumn('SUBSCRIPTION_NUMBER', 'SubscriptionNumber', 'VARCHAR', false, 50);

		$tMap->addColumn('TITLE', 'Title', 'VARCHAR', true, 255);

		$tMap->addColumn('SORT_TITLE', 'SortTitle', 'VARCHAR', true, 255);

		$tMap->addColumn('ALT_TITLE', 'AltTitle', 'VARCHAR', false, 255);

		$tMap->addColumn('LANGUAGE', 'Language', 'VARCHAR', true, 25);

		$tMap->addColumn('DESCRIPTION', 'Description', 'LONGVARCHAR', false, null);

		$tMap->addColumn('PUBLIC_NOTE', 'PublicNote', 'LONGVARCHAR', false, null);

		$tMap->addColumn('SUPPRESSION', 'Suppression', 'BOOLEAN', true, null);

		$tMap->addColumn('PRODUCT_UNAVAILABLE', 'ProductUnavailable', 'BOOLEAN', true, null);

		$tMap->addForeignKey('ACQ_ID', 'AcqId', 'INTEGER', 'acquisitions', 'ID', false, null);

		$tMap->addForeignKey('ACCESS_INFO_ID', 'AccessInfoId', 'INTEGER', 'access_infos', 'ID', false, null);

		$tMap->addForeignKey('ADMIN_INFO_ID', 'AdminInfoId', 'INTEGER', 'admin_infos', 'ID', false, null);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', true, null);

		$tMap->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', true, null);

		$tMap->addColumn('DELETED_AT', 'DeletedAt', 'TIMESTAMP', false, null);

	} // doBuild()

} // EResourceMapBuilder
