<?php


/**
 * This class adds structure of 'eresource_db_subject_assoc' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Jul 21 11:41:56 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class EResourceDbSubjectAssocMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.EResourceDbSubjectAssocMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(EResourceDbSubjectAssocPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(EResourceDbSubjectAssocPeer::TABLE_NAME);
		$tMap->setPhpName('EResourceDbSubjectAssoc');
		$tMap->setClassname('EResourceDbSubjectAssoc');

		$tMap->setUseIdGenerator(false);

		$tMap->addForeignPrimaryKey('ER_ID', 'ErId', 'INTEGER' , 'eresources', 'ID', true, null);

		$tMap->addForeignPrimaryKey('DB_SUBJECT_ID', 'DbSubjectId', 'INTEGER' , 'db_subjects', 'ID', true, null);

	} // doBuild()

} // EResourceDbSubjectAssocMapBuilder
