<?php


/**
 * This class adds structure of 'ip_ranges' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Jul 21 11:41:56 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class IpRangeMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.IpRangeMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(IpRangePeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(IpRangePeer::TABLE_NAME);
		$tMap->setPhpName('IpRange');
		$tMap->setClassname('IpRange');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addForeignKey('LIB_ID', 'LibId', 'INTEGER', 'libraries', 'ID', true, null);

		$tMap->addColumn('START_IP', 'StartIp', 'VARCHAR', true, 15);

		$tMap->addColumn('END_IP', 'EndIp', 'VARCHAR', false, 15);

		$tMap->addColumn('ACTIVE_INDICATOR', 'ActiveIndicator', 'BOOLEAN', true, null);

		$tMap->addColumn('PROXY_INDICATOR', 'ProxyIndicator', 'BOOLEAN', true, null);

		$tMap->addColumn('NOTE', 'Note', 'VARCHAR', false, 255);

		$tMap->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', true, null);

	} // doBuild()

} // IpRangeMapBuilder
