<?php

/**
 * Base class that represents a row from the 'libraries' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Tue May 11 17:37:53 2010
 *
 * @package    lib.model.om
 */
abstract class BaseLibrary extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        LibraryPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the name field.
	 * @var        string
	 */
	protected $name;

	/**
	 * The value for the code field.
	 * @var        string
	 */
	protected $code;

	/**
	 * The value for the alt_name field.
	 * @var        string
	 */
	protected $alt_name;

	/**
	 * The value for the address field.
	 * @var        string
	 */
	protected $address;

	/**
	 * The value for the ezproxy_host field.
	 * @var        string
	 */
	protected $ezproxy_host;

	/**
	 * The value for the ezproxy_key field.
	 * @var        string
	 */
	protected $ezproxy_key;

	/**
	 * The value for the cost_center_no field.
	 * @var        int
	 */
	protected $cost_center_no;

	/**
	 * The value for the fte field.
	 * @var        int
	 */
	protected $fte;

	/**
	 * The value for the note field.
	 * @var        string
	 */
	protected $note;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * @var        array AcqLibAssoc[] Collection to store aggregation of AcqLibAssoc objects.
	 */
	protected $collAcqLibAssocs;

	/**
	 * @var        Criteria The criteria used to select the current contents of collAcqLibAssocs.
	 */
	private $lastAcqLibAssocCriteria = null;

	/**
	 * @var        array IpRange[] Collection to store aggregation of IpRange objects.
	 */
	protected $collIpRanges;

	/**
	 * @var        Criteria The criteria used to select the current contents of collIpRanges.
	 */
	private $lastIpRangeCriteria = null;

	/**
	 * @var        array UsageAttempt[] Collection to store aggregation of UsageAttempt objects.
	 */
	protected $collUsageAttempts;

	/**
	 * @var        Criteria The criteria used to select the current contents of collUsageAttempts.
	 */
	private $lastUsageAttemptCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'LibraryPeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [name] column value.
	 * 
	 * @return     string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Get the [code] column value.
	 * 
	 * @return     string
	 */
	public function getCode()
	{
		return $this->code;
	}

	/**
	 * Get the [alt_name] column value.
	 * 
	 * @return     string
	 */
	public function getAltName()
	{
		return $this->alt_name;
	}

	/**
	 * Get the [address] column value.
	 * 
	 * @return     string
	 */
	public function getAddress()
	{
		return $this->address;
	}

	/**
	 * Get the [ezproxy_host] column value.
	 * 
	 * @return     string
	 */
	public function getEzproxyHost()
	{
		return $this->ezproxy_host;
	}

	/**
	 * Get the [ezproxy_key] column value.
	 * 
	 * @return     string
	 */
	public function getEzproxyKey()
	{
		return $this->ezproxy_key;
	}

	/**
	 * Get the [cost_center_no] column value.
	 * 
	 * @return     int
	 */
	public function getCostCenterNo()
	{
		return $this->cost_center_no;
	}

	/**
	 * Get the [fte] column value.
	 * 
	 * @return     int
	 */
	public function getFte()
	{
		return $this->fte;
	}

	/**
	 * Get the [note] column value.
	 * 
	 * @return     string
	 */
	public function getNote()
	{
		return $this->note;
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Library The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = LibraryPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [name] column.
	 * 
	 * @param      string $v new value
	 * @return     Library The current object (for fluent API support)
	 */
	public function setName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->name !== $v) {
			$this->name = $v;
			$this->modifiedColumns[] = LibraryPeer::NAME;
		}

		return $this;
	} // setName()

	/**
	 * Set the value of [code] column.
	 * 
	 * @param      string $v new value
	 * @return     Library The current object (for fluent API support)
	 */
	public function setCode($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->code !== $v) {
			$this->code = $v;
			$this->modifiedColumns[] = LibraryPeer::CODE;
		}

		return $this;
	} // setCode()

	/**
	 * Set the value of [alt_name] column.
	 * 
	 * @param      string $v new value
	 * @return     Library The current object (for fluent API support)
	 */
	public function setAltName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->alt_name !== $v) {
			$this->alt_name = $v;
			$this->modifiedColumns[] = LibraryPeer::ALT_NAME;
		}

		return $this;
	} // setAltName()

	/**
	 * Set the value of [address] column.
	 * 
	 * @param      string $v new value
	 * @return     Library The current object (for fluent API support)
	 */
	public function setAddress($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->address !== $v) {
			$this->address = $v;
			$this->modifiedColumns[] = LibraryPeer::ADDRESS;
		}

		return $this;
	} // setAddress()

	/**
	 * Set the value of [ezproxy_host] column.
	 * 
	 * @param      string $v new value
	 * @return     Library The current object (for fluent API support)
	 */
	public function setEzproxyHost($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->ezproxy_host !== $v) {
			$this->ezproxy_host = $v;
			$this->modifiedColumns[] = LibraryPeer::EZPROXY_HOST;
		}

		return $this;
	} // setEzproxyHost()

	/**
	 * Set the value of [ezproxy_key] column.
	 * 
	 * @param      string $v new value
	 * @return     Library The current object (for fluent API support)
	 */
	public function setEzproxyKey($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->ezproxy_key !== $v) {
			$this->ezproxy_key = $v;
			$this->modifiedColumns[] = LibraryPeer::EZPROXY_KEY;
		}

		return $this;
	} // setEzproxyKey()

	/**
	 * Set the value of [cost_center_no] column.
	 * 
	 * @param      int $v new value
	 * @return     Library The current object (for fluent API support)
	 */
	public function setCostCenterNo($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->cost_center_no !== $v) {
			$this->cost_center_no = $v;
			$this->modifiedColumns[] = LibraryPeer::COST_CENTER_NO;
		}

		return $this;
	} // setCostCenterNo()

	/**
	 * Set the value of [fte] column.
	 * 
	 * @param      int $v new value
	 * @return     Library The current object (for fluent API support)
	 */
	public function setFte($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->fte !== $v) {
			$this->fte = $v;
			$this->modifiedColumns[] = LibraryPeer::FTE;
		}

		return $this;
	} // setFte()

	/**
	 * Set the value of [note] column.
	 * 
	 * @param      string $v new value
	 * @return     Library The current object (for fluent API support)
	 */
	public function setNote($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->note !== $v) {
			$this->note = $v;
			$this->modifiedColumns[] = LibraryPeer::NOTE;
		}

		return $this;
	} // setNote()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Library The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = LibraryPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->name = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->code = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->alt_name = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->address = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->ezproxy_host = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->ezproxy_key = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->cost_center_no = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->fte = ($row[$startcol + 8] !== null) ? (int) $row[$startcol + 8] : null;
			$this->note = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->updated_at = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 11; // 11 = LibraryPeer::NUM_COLUMNS - LibraryPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Library object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(LibraryPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = LibraryPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->collAcqLibAssocs = null;
			$this->lastAcqLibAssocCriteria = null;

			$this->collIpRanges = null;
			$this->lastIpRangeCriteria = null;

			$this->collUsageAttempts = null;
			$this->lastUsageAttemptCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(LibraryPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseLibrary:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				LibraryPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseLibrary:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(LibraryPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseLibrary:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			// symfony_timestampable behavior
			if ($this->isModified() && !$this->isColumnModified(LibraryPeer::UPDATED_AT))
			{
			  $this->setUpdatedAt(time());
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseLibrary:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				LibraryPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = LibraryPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = LibraryPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += LibraryPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collAcqLibAssocs !== null) {
				foreach ($this->collAcqLibAssocs as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collIpRanges !== null) {
				foreach ($this->collIpRanges as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collUsageAttempts !== null) {
				foreach ($this->collUsageAttempts as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = LibraryPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collAcqLibAssocs !== null) {
					foreach ($this->collAcqLibAssocs as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collIpRanges !== null) {
					foreach ($this->collIpRanges as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collUsageAttempts !== null) {
					foreach ($this->collUsageAttempts as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = LibraryPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getName();
				break;
			case 2:
				return $this->getCode();
				break;
			case 3:
				return $this->getAltName();
				break;
			case 4:
				return $this->getAddress();
				break;
			case 5:
				return $this->getEzproxyHost();
				break;
			case 6:
				return $this->getEzproxyKey();
				break;
			case 7:
				return $this->getCostCenterNo();
				break;
			case 8:
				return $this->getFte();
				break;
			case 9:
				return $this->getNote();
				break;
			case 10:
				return $this->getUpdatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = LibraryPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getName(),
			$keys[2] => $this->getCode(),
			$keys[3] => $this->getAltName(),
			$keys[4] => $this->getAddress(),
			$keys[5] => $this->getEzproxyHost(),
			$keys[6] => $this->getEzproxyKey(),
			$keys[7] => $this->getCostCenterNo(),
			$keys[8] => $this->getFte(),
			$keys[9] => $this->getNote(),
			$keys[10] => $this->getUpdatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = LibraryPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setName($value);
				break;
			case 2:
				$this->setCode($value);
				break;
			case 3:
				$this->setAltName($value);
				break;
			case 4:
				$this->setAddress($value);
				break;
			case 5:
				$this->setEzproxyHost($value);
				break;
			case 6:
				$this->setEzproxyKey($value);
				break;
			case 7:
				$this->setCostCenterNo($value);
				break;
			case 8:
				$this->setFte($value);
				break;
			case 9:
				$this->setNote($value);
				break;
			case 10:
				$this->setUpdatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = LibraryPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setName($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setCode($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setAltName($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setAddress($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setEzproxyHost($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setEzproxyKey($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setCostCenterNo($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setFte($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setNote($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setUpdatedAt($arr[$keys[10]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(LibraryPeer::DATABASE_NAME);

		if ($this->isColumnModified(LibraryPeer::ID)) $criteria->add(LibraryPeer::ID, $this->id);
		if ($this->isColumnModified(LibraryPeer::NAME)) $criteria->add(LibraryPeer::NAME, $this->name);
		if ($this->isColumnModified(LibraryPeer::CODE)) $criteria->add(LibraryPeer::CODE, $this->code);
		if ($this->isColumnModified(LibraryPeer::ALT_NAME)) $criteria->add(LibraryPeer::ALT_NAME, $this->alt_name);
		if ($this->isColumnModified(LibraryPeer::ADDRESS)) $criteria->add(LibraryPeer::ADDRESS, $this->address);
		if ($this->isColumnModified(LibraryPeer::EZPROXY_HOST)) $criteria->add(LibraryPeer::EZPROXY_HOST, $this->ezproxy_host);
		if ($this->isColumnModified(LibraryPeer::EZPROXY_KEY)) $criteria->add(LibraryPeer::EZPROXY_KEY, $this->ezproxy_key);
		if ($this->isColumnModified(LibraryPeer::COST_CENTER_NO)) $criteria->add(LibraryPeer::COST_CENTER_NO, $this->cost_center_no);
		if ($this->isColumnModified(LibraryPeer::FTE)) $criteria->add(LibraryPeer::FTE, $this->fte);
		if ($this->isColumnModified(LibraryPeer::NOTE)) $criteria->add(LibraryPeer::NOTE, $this->note);
		if ($this->isColumnModified(LibraryPeer::UPDATED_AT)) $criteria->add(LibraryPeer::UPDATED_AT, $this->updated_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(LibraryPeer::DATABASE_NAME);

		$criteria->add(LibraryPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Library (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setName($this->name);

		$copyObj->setCode($this->code);

		$copyObj->setAltName($this->alt_name);

		$copyObj->setAddress($this->address);

		$copyObj->setEzproxyHost($this->ezproxy_host);

		$copyObj->setEzproxyKey($this->ezproxy_key);

		$copyObj->setCostCenterNo($this->cost_center_no);

		$copyObj->setFte($this->fte);

		$copyObj->setNote($this->note);

		$copyObj->setUpdatedAt($this->updated_at);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getAcqLibAssocs() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addAcqLibAssoc($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getIpRanges() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addIpRange($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getUsageAttempts() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addUsageAttempt($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Library Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     LibraryPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new LibraryPeer();
		}
		return self::$peer;
	}

	/**
	 * Clears out the collAcqLibAssocs collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addAcqLibAssocs()
	 */
	public function clearAcqLibAssocs()
	{
		$this->collAcqLibAssocs = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collAcqLibAssocs collection (array).
	 *
	 * By default this just sets the collAcqLibAssocs collection to an empty array (like clearcollAcqLibAssocs());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initAcqLibAssocs()
	{
		$this->collAcqLibAssocs = array();
	}

	/**
	 * Gets an array of AcqLibAssoc objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Library has previously been saved, it will retrieve
	 * related AcqLibAssocs from storage. If this Library is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array AcqLibAssoc[]
	 * @throws     PropelException
	 */
	public function getAcqLibAssocs($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(LibraryPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAcqLibAssocs === null) {
			if ($this->isNew()) {
			   $this->collAcqLibAssocs = array();
			} else {

				$criteria->add(AcqLibAssocPeer::LIB_ID, $this->id);

				AcqLibAssocPeer::addSelectColumns($criteria);
				$this->collAcqLibAssocs = AcqLibAssocPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(AcqLibAssocPeer::LIB_ID, $this->id);

				AcqLibAssocPeer::addSelectColumns($criteria);
				if (!isset($this->lastAcqLibAssocCriteria) || !$this->lastAcqLibAssocCriteria->equals($criteria)) {
					$this->collAcqLibAssocs = AcqLibAssocPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastAcqLibAssocCriteria = $criteria;
		return $this->collAcqLibAssocs;
	}

	/**
	 * Returns the number of related AcqLibAssoc objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related AcqLibAssoc objects.
	 * @throws     PropelException
	 */
	public function countAcqLibAssocs(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(LibraryPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collAcqLibAssocs === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(AcqLibAssocPeer::LIB_ID, $this->id);

				$count = AcqLibAssocPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(AcqLibAssocPeer::LIB_ID, $this->id);

				if (!isset($this->lastAcqLibAssocCriteria) || !$this->lastAcqLibAssocCriteria->equals($criteria)) {
					$count = AcqLibAssocPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collAcqLibAssocs);
				}
			} else {
				$count = count($this->collAcqLibAssocs);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a AcqLibAssoc object to this object
	 * through the AcqLibAssoc foreign key attribute.
	 *
	 * @param      AcqLibAssoc $l AcqLibAssoc
	 * @return     void
	 * @throws     PropelException
	 */
	public function addAcqLibAssoc(AcqLibAssoc $l)
	{
		if ($this->collAcqLibAssocs === null) {
			$this->initAcqLibAssocs();
		}
		if (!in_array($l, $this->collAcqLibAssocs, true)) { // only add it if the **same** object is not already associated
			array_push($this->collAcqLibAssocs, $l);
			$l->setLibrary($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Library is new, it will return
	 * an empty collection; or if this Library has previously
	 * been saved, it will retrieve related AcqLibAssocs from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Library.
	 */
	public function getAcqLibAssocsJoinAcquisition($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(LibraryPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAcqLibAssocs === null) {
			if ($this->isNew()) {
				$this->collAcqLibAssocs = array();
			} else {

				$criteria->add(AcqLibAssocPeer::LIB_ID, $this->id);

				$this->collAcqLibAssocs = AcqLibAssocPeer::doSelectJoinAcquisition($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(AcqLibAssocPeer::LIB_ID, $this->id);

			if (!isset($this->lastAcqLibAssocCriteria) || !$this->lastAcqLibAssocCriteria->equals($criteria)) {
				$this->collAcqLibAssocs = AcqLibAssocPeer::doSelectJoinAcquisition($criteria, $con, $join_behavior);
			}
		}
		$this->lastAcqLibAssocCriteria = $criteria;

		return $this->collAcqLibAssocs;
	}

	/**
	 * Clears out the collIpRanges collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addIpRanges()
	 */
	public function clearIpRanges()
	{
		$this->collIpRanges = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collIpRanges collection (array).
	 *
	 * By default this just sets the collIpRanges collection to an empty array (like clearcollIpRanges());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initIpRanges()
	{
		$this->collIpRanges = array();
	}

	/**
	 * Gets an array of IpRange objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Library has previously been saved, it will retrieve
	 * related IpRanges from storage. If this Library is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array IpRange[]
	 * @throws     PropelException
	 */
	public function getIpRanges($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(LibraryPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collIpRanges === null) {
			if ($this->isNew()) {
			   $this->collIpRanges = array();
			} else {

				$criteria->add(IpRangePeer::LIB_ID, $this->id);

				IpRangePeer::addSelectColumns($criteria);
				$this->collIpRanges = IpRangePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(IpRangePeer::LIB_ID, $this->id);

				IpRangePeer::addSelectColumns($criteria);
				if (!isset($this->lastIpRangeCriteria) || !$this->lastIpRangeCriteria->equals($criteria)) {
					$this->collIpRanges = IpRangePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastIpRangeCriteria = $criteria;
		return $this->collIpRanges;
	}

	/**
	 * Returns the number of related IpRange objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related IpRange objects.
	 * @throws     PropelException
	 */
	public function countIpRanges(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(LibraryPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collIpRanges === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(IpRangePeer::LIB_ID, $this->id);

				$count = IpRangePeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(IpRangePeer::LIB_ID, $this->id);

				if (!isset($this->lastIpRangeCriteria) || !$this->lastIpRangeCriteria->equals($criteria)) {
					$count = IpRangePeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collIpRanges);
				}
			} else {
				$count = count($this->collIpRanges);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a IpRange object to this object
	 * through the IpRange foreign key attribute.
	 *
	 * @param      IpRange $l IpRange
	 * @return     void
	 * @throws     PropelException
	 */
	public function addIpRange(IpRange $l)
	{
		if ($this->collIpRanges === null) {
			$this->initIpRanges();
		}
		if (!in_array($l, $this->collIpRanges, true)) { // only add it if the **same** object is not already associated
			array_push($this->collIpRanges, $l);
			$l->setLibrary($this);
		}
	}

	/**
	 * Clears out the collUsageAttempts collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addUsageAttempts()
	 */
	public function clearUsageAttempts()
	{
		$this->collUsageAttempts = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collUsageAttempts collection (array).
	 *
	 * By default this just sets the collUsageAttempts collection to an empty array (like clearcollUsageAttempts());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initUsageAttempts()
	{
		$this->collUsageAttempts = array();
	}

	/**
	 * Gets an array of UsageAttempt objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Library has previously been saved, it will retrieve
	 * related UsageAttempts from storage. If this Library is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array UsageAttempt[]
	 * @throws     PropelException
	 */
	public function getUsageAttempts($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(LibraryPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collUsageAttempts === null) {
			if ($this->isNew()) {
			   $this->collUsageAttempts = array();
			} else {

				$criteria->add(UsageAttemptPeer::LIB_ID, $this->id);

				UsageAttemptPeer::addSelectColumns($criteria);
				$this->collUsageAttempts = UsageAttemptPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(UsageAttemptPeer::LIB_ID, $this->id);

				UsageAttemptPeer::addSelectColumns($criteria);
				if (!isset($this->lastUsageAttemptCriteria) || !$this->lastUsageAttemptCriteria->equals($criteria)) {
					$this->collUsageAttempts = UsageAttemptPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastUsageAttemptCriteria = $criteria;
		return $this->collUsageAttempts;
	}

	/**
	 * Returns the number of related UsageAttempt objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related UsageAttempt objects.
	 * @throws     PropelException
	 */
	public function countUsageAttempts(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(LibraryPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collUsageAttempts === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(UsageAttemptPeer::LIB_ID, $this->id);

				$count = UsageAttemptPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(UsageAttemptPeer::LIB_ID, $this->id);

				if (!isset($this->lastUsageAttemptCriteria) || !$this->lastUsageAttemptCriteria->equals($criteria)) {
					$count = UsageAttemptPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collUsageAttempts);
				}
			} else {
				$count = count($this->collUsageAttempts);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a UsageAttempt object to this object
	 * through the UsageAttempt foreign key attribute.
	 *
	 * @param      UsageAttempt $l UsageAttempt
	 * @return     void
	 * @throws     PropelException
	 */
	public function addUsageAttempt(UsageAttempt $l)
	{
		if ($this->collUsageAttempts === null) {
			$this->initUsageAttempts();
		}
		if (!in_array($l, $this->collUsageAttempts, true)) { // only add it if the **same** object is not already associated
			array_push($this->collUsageAttempts, $l);
			$l->setLibrary($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Library is new, it will return
	 * an empty collection; or if this Library has previously
	 * been saved, it will retrieve related UsageAttempts from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Library.
	 */
	public function getUsageAttemptsJoinEResource($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(LibraryPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collUsageAttempts === null) {
			if ($this->isNew()) {
				$this->collUsageAttempts = array();
			} else {

				$criteria->add(UsageAttemptPeer::LIB_ID, $this->id);

				$this->collUsageAttempts = UsageAttemptPeer::doSelectJoinEResource($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(UsageAttemptPeer::LIB_ID, $this->id);

			if (!isset($this->lastUsageAttemptCriteria) || !$this->lastUsageAttemptCriteria->equals($criteria)) {
				$this->collUsageAttempts = UsageAttemptPeer::doSelectJoinEResource($criteria, $con, $join_behavior);
			}
		}
		$this->lastUsageAttemptCriteria = $criteria;

		return $this->collUsageAttempts;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collAcqLibAssocs) {
				foreach ((array) $this->collAcqLibAssocs as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collIpRanges) {
				foreach ((array) $this->collIpRanges as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collUsageAttempts) {
				foreach ((array) $this->collUsageAttempts as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collAcqLibAssocs = null;
		$this->collIpRanges = null;
		$this->collUsageAttempts = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseLibrary:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseLibrary::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseLibrary
