default:
  http_metas:
    content-type: application/json

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    []
  javascripts:    []

  has_layout:     off

