parameters:
#    yitznewton_freerms.example.class: Yitznewton\FreermsBundle\Example

services:
#    yitznewton_freerms.example:
#        class: %yitznewton_freerms.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
