contact:
  class: sfPropelRouteCollection
  options:
    model:                Contact
    module:               contact
    prefix_path:          /contact
    column:               id
    with_wildcard_routes: true

e_resource:
  class: sfPropelRouteCollection
  options:
    model:               EResource
    module:              database
    prefix_path:         /database
    column:              id
    with_wildcard_routes: true

subject:
  class: sfPropelRouteCollection
  options:
    model:               DbSubject
    module:              subject
    prefix_path:         /subject
    column:              id
    with_wildcard_routes: true

homepage:
  url:   /
  param: { module: database, action: index }

database_featured:
  url:   /featured
  param: { module: database, action: featured }

ajax_er_db_subject_remove:
  url:   /subject/ajax/remove/*
  param: { module: subject, action: ajaxEResourceDelete }

ajax_database_search:
  url:   /database/ajax/search/*
  param: { module: database, action: ajaxSearch }

ajax_database_unfeature:
  url:   /database/ajax/unfeature/*
  param: { module: database, action: ajaxUnfeature }

default_index:
  url:   /:module
  param: { action: index }

default_update:
  url:   /:module/update/:id/*
  param: { action: update }

default:
  url:   /:module/:action/*
  param: ~
