db_subject_subject:
  class: sfPropelRouteCollection
  options:
    model:                DbSubject
    module:               subject
    prefix_path:          /subject
    column:               id
    with_wildcard_routes: true

db_subject:
  class: sfPropelRouteCollection
  options:
    model:                DbSubject
    module:               dbsubject
    prefix_path:          /dbsubject
    column:               id
    with_wildcard_routes: true

organization:
  class: sfPropelRouteCollection
  options:
    model:                Organization
    module:               organization
    prefix_path:          /organization
    column:               id
    with_wildcard_routes: true

ip_range_ip:
  class: sfPropelRouteCollection
  options:
    model:                IpRange
    module:               ip
    prefix_path:          /ip
    column:               id
    with_wildcard_routes: true

ip_range:
  class: sfPropelRouteCollection
  options:
    model:                IpRange
    module:               ipRange
    prefix_path:          /ipRange
    column:               id
    with_wildcard_routes: true

library:
  class: sfPropelRouteCollection
  options:
    model:                Library
    module:               library
    prefix_path:          /library
    column:               id
    with_wildcard_routes: true

contact:
  class: sfPropelRouteCollection
  options:
    model:                Contact
    module:               contact
    prefix_path:          /contact
    column:               id
    with_wildcard_routes: true

e_resource:
  class: sfPropelRouteCollection
  options:
    model:               EResource
    module:              database
    prefix_path:         /database
    column:              id
    with_wildcard_routes: true

homepage:
  url:   /
  param: { module: database, action: index }

login:
  url:   /login
  param: { module: user, action: login }

logout:
  url:   /logout
  param: { module: user, action: logout }

ip_registration:
  url:   /ip/registration
  param: { module: ip, action: registration }

ip_autoregister:
  url:   /ip/autoregister
  param: { module: ip, action: autoregister }

default_export:
  url:   /:module/export/*
  param: { action: export }

default_index:
  url:   /:module
  param: { action: index }

default_new:
  url:   /:module/new/*
  param: { action: new }

default_create:
  url:   /:module/create/*
  param: { action: create }

default_update:
  url:   /:module/update/:id/*
  param: { action: update }

default_delete:
  url:   /:module/delete/:id/*
  param: { action: delete }

default_edit:
  url:   /:module/:id/*
  param: { action: edit }
