<?php

/**
 * Database
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    freerms
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Database extends BaseDatabase
{
  /**
   * @return array int[]
   */
  public function getLibraryIds()
  {
    $ids = array();

    foreach ($this->getLibraries() as $library) {
      $ids[] = $library->getId();
    }

    return $ids;
  }
}

