generator:
  class: sfPropelGenerator
  param:
    model_class:           EResource
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              e_resource
    plural:                e_resources
    route_prefix:          e_resource
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        title_link:  { label: Title }
        suppression: { label: Suppress }
        product_unavailable: { label: Unavailable }
      list:
        title: ''
        display: [_title_link, suppression, product_unavailable]
        batch_actions: {}
        object_actions: {}
      filter:
        display: [title, suppression, product_unavailable]
      form:    ~
      edit:    ~
      new:     ~
