homepage:
  url: /
  params: { module: database, action: index }

database_index:
  url: /
  params: { module: database, action: index }

database_index_0:
  url: /database
  params: { module: database, action: index }

database_index_1:
  url: /database/
  params: { module: database, action: index }

database_access:
  url: /database/:id
  params: { module: database, action: access }
  requirements:
    id: \d+

proxy_url:
  url: /url/:url
  params: { module: database, action: directUrl }
  requirements:
    url: http.+

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

