homepage:
  url: /
  params: { module: database, action: index }

database_index:
  url: /
  params: { module: database, action: index }

database_index_0:
  url: /database
  params: { module: database, action: index }

database_index_1:
  url: /database/
  params: { module: database, action: index }

database_access:
  url: /database/:id
  params: { module: database, action: access }
  requirements:
    id: \d+

database_access_alt:
  url: /database/alt/:alt_id
  params: { module: database, action: access }

access_refer:
  url: /refer
  params: { module: access, action: refererAccess }

proxy_url:
  # needs to be wildcard to match slashes in URL
  url: /url/*
  params: { module: access, action: ezproxyUrlAccess }

direct_refer_url:
  # legacy links; insecure, so replacing with proxied links
  # needs to be wildcard to match slashes in URL
  url: /direct-refer/*
  params: { module: access, action: ezproxyUrlAccess }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

