generator:
  class: sfDoctrineGenerator
  param:
    model_class:           IpRange
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ip_range
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        start_ip:
          label: Start IP
        end_ip:
          label: End IP
        is_active:
          label: Active
        is_excluded:
          label: Excluded
      list:
        title: IP Ranges
        display: [=start_ip, =end_ip, is_active, is_excluded]
        sort: [start_ip_sort, asc]
      filter:
        display: [ip, is_active, is_excluded]
      form:
        fields:
          is_excluded:
            help: |
              e.g. internal IP address used for testing, or to override
                autodetected library affiliation
      edit:
        title: Edit IP Range
      new:
        title: New IP Range
