<?php

require 'lib/model/om/BaseAutoEmailIpRegEvent.php';


/**
 * Skeleton subclass for representing a row from the 'auto_email_ip_reg_events' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Mon May 17 17:27:32 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class AutoEmailIpRegEvent extends BaseAutoEmailIpRegEvent {
  public function __toString()
  {
    if ( ! $this->getOldStartIp() ) {
      return 'New: ' . $this->getIpRange() . ' (' . $this->getIpRange()->getLibrary()->getName() . ')';
    }

    $old = new IpRange();
    $old->setStartIp( $this->getOldStartIp() );
    $old->setEndIp( $this->getOldEndIp() );

    if ( ! $this->getNewStartIp() ) {
      return 'Deleted: ' . $old;
    }

    $old = new IpRange();
    $old->setStartIp( $this->getOldStartIp() );
    $old->setEndIp( $this->getOldEndIp() );

    return "Modified: $old becomes " . $this->getIpRange() . ' (' . $this->getIpRange()->getLibrary() . ')';
  }
} // AutoEmailIpRegEvent
