<?php

require 'lib/model/om/BaseContact.php';


/**
 * Skeleton subclass for representing a row from the 'contacts' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Tue May 11 17:37:08 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Contact extends BaseContact {
  public function __toString()
  {
    return $this->getFirstName() . ' ' . $this->getLastName();
  }

  public function getFirstContactEmail()
  {
    $emails = $this->getContactEmails();

    if ( $emails ) {
      return $emails[0];
    }
    else {
      return false;
    }
  }

  public function getFirstContactPhone()
  {
    $phones = $this->getContactPhones();

    if ( $phones ) {
      return $phones[0];
    }
    else {
      return false;
    }
  }
} // Contact
