<?php

require 'lib/model/om/BaseIpNotificationMethodPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'ip_notification_methods' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Tue May 11 17:37:11 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class IpNotificationMethodPeer extends BaseIpNotificationMethodPeer {

} // IpNotificationMethodPeer
