<?php

require 'lib/model/om/BaseIpRegEvent.php';


/**
 * Skeleton subclass for representing a row from the 'ip_reg_events' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Thu May 13 10:33:23 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class IpRegEvent extends BaseIpRegEvent {
  public function initialize( IpRange $ip_range )
  {
    $this->setIpRangeId( $ip_range->getId() );

    if ( ! $ip_range->isNew() ) {
      $this->setOldStartIp( $ip_range->getStartIp() );
      $this->setOldEndIp( $ip_range->getEndIp() );
    }
  }
} // IpRegEvent
