<?php

require 'lib/model/om/BaseManualEmailIpRegContact.php';


/**
 * Skeleton subclass for representing a row from the 'manual_email_ip_reg_contacts' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Tue May 18 13:15:21 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ManualEmailIpRegContact extends BaseManualEmailIpRegContact {

} // ManualEmailIpRegContact
