# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

database:
  url:   /database/:id/*
  param: { module: default, action: database }

library:
  url:   /library/:id/*
  param: { module: default, action: library }

url_by_library:
  url:   /url/by-library/:filter/*
  param: { module: default, action: url, by: library }

url_by_host:
  url:   /url/by-host/:filter/*
  param: { module: default, action: url, by: host }
  requirements: { filter: '.*' }

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

