# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:
    - /sfDoctrinePlugin/css/global.css
    - /sfDoctrinePlugin/css/default.css
    - reports.css

  javascripts:
    - xui.js: { condition: !IE }
    - xui-ie.js: { condition: IE }
    - /js/lib/FR.js
    - /js/lib/FR/Reports.js
    - reports.js

  has_layout:     true
  layout:         layout
