all:
  institution-name: Touro College Libraries
  local-erms-name:  the system
  admin-email:      systems.library@touro.edu
  support-email:    systems.library@touro.edu
  
  user-api:
    url-mask:           http://users.example.com/api?username=%s&password=%s
    credential-prefix:  freerms
  
  access:
    default-handler-onsite: BaseAccessHandler
    default-handler-offsite: RefererAccessHandler

  sf_guard_plugin_signin_form: touroUsersSigninForm
