all:
  institution-name: Wassamatta University Libraries
  local-erms-name:  WU-ERM
  admin-email:      admin@example.com
  support-email:    help@example.com
  
  access:
    default-handler-onsite: BaseAccessHandler
    default-handler-offsite: RefererAccessHandler
