dev:
  propel:
    param:
      classname:  DebugPDO

test:
  propel:
    param:
      classname:  DebugPDO

all:
  propel:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=freerms_live;host=localhost
      username:   freerms
      password:    
      encoding:   utf8
      persistent: true
      pooling:    true
  propel_users:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=users;host=localhost
      username:   users
      password:   wan1tkwsn
      encoding:   utf8
      persistent: true
      pooling:    true
