all:
  .options:
    offsite-testing-ip-addresses:
      # YBS
      - 192.168.65.184
      # Dr. Kadish - until we implement option to manually force login
      # on-campus
      - 192.168.47.113
  
  homepage-redirect-url: http://www.tourolib.org/
