rendering: ~
security:  ~

affiliation:
  class: freermsAffiliationFilter
freerms_cache:
  class: freermsResolverCacheFilter
  
# insert your own filters here

cache:     ~
common:
  class: sfCommonFilter
execution: ~
