rendering: ~
security:  ~

affiliation:
  class: freermsAffiliationFilter
layout:
  class: touroLayoutFilter
  
# insert your own filters here

cache:     ~
common:
  class: sfCommonFilter
execution: ~
