homepage:
  url:   /
  param: { module: database, action: index }

database_access:
  url:   /database/:id
  param: { module: database, action: access }

database_access_alt_id:
  url:   /database/alt/:alt_id
  param: { module: database, action: access }

database_refer:
  url:   /refer
  param: { module: database, action: refer }

database_direct_url:
  url:   /url/*
  param: { module: database, action: directUrl }

database_direct_refer:
  url:   /direct-refer/*
  param: { module: database, action: directRefer }
  
logout:
  url:   /logout
  param: { module: user, action: logout }
