default:
  http_metas:
    content-type: text/html

  metas:
    description:  Electronic Resource Management System
    title:        <?php echo sfConfig::get('app_local-erms-name') ?>

  stylesheets:    []
  javascripts:    [resolver.js]

  has_layout:     true
  layout:         layout
