default:
  http_metas:
    content-type: text/html

  metas:
    description:  Electronic Resource Management System
    title:        <?php echo sfConfig::get('app_local-erms-name') ?>

  stylesheets:
    - resolver.css: { media: all }
  
  javascripts:
    - jquery.cookie.js
    - global.js
    - resolver.js

  has_layout:     true
  layout:         tc

  components:
    logoutLink: [database, logoutLink]
