generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardGroup
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_group
    with_doctrine_route:   true

    config:
      list:
        title: false
        display: [=name, description]

      filter:
        display: [name, description]

      form:
        display: [name, description, permissions_list]

      edit:
        title: Editing Group "%%name%%"

      new:
        title: New Group
