<?php


/**
 * Skeleton subclass for representing a row from the 'statuses' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Jun  3 13:23:15 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.touroUsersPlugin.lib.model
 */
class Status extends BaseStatus {

} // Status
