<?php


/**
 * Skeleton subclass for representing a row from the 'libraries' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Jun 13 12:32:37 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.touroUsersPlugin.lib.model
 */
class TouroUsersLibrary extends BaseTouroUsersLibrary {

} // TouroUsersLibrary
