IpRange:
  tableName: ip_range
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    start_ip:
      type: string(15)
      notnull: true
    end_ip:
      type: string(15)
      notnull: true
    start_ip_sort:
      type: string(12)
      notnull: true
    end_ip_sort:
      type: string(12)
      notnull: true
    note:
      type: clob
    is_active:
      type: boolean
      notnull: true
      default: true
    is_excluded:
      type: boolean
      notnull: true
      default: false
    library_id:
      type: integer
      notnull: true
  relations:
    Library:
      onDelete: RESTRICT
      foreignAlias: IpRanges

Library:
  tableName: library
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    name:
      type: string
      notnull: true
    code:
      type: string(10)
      notnull: true
      unique: true
    show_featured_subjects:
      type: boolean
      notnull: true
      default: true
    note:
      type: clob

