Database:
  tableName: database
  actAs: [Timestampable]
  columns:
    alt_id:
      type: string(10)
      unique: true
    title:
      type: string(255)
      notnull: true
    sort_title:
      type: string(255)
      notnull: true
    access_url:
      type: string(255)
      notnull: true
    access_action_onsite:
      type: string(255)
      notnull: true
      default: baseAccess
    access_action_offsite:
      type: string(255)
      notnull: true
      default: baseAccess
    description:
      type: clob
    public_note:
      type: clob
    referral_note:
      type: clob
    is_hidden:
      type: boolean
      notnull: true
      default: false
    is_unavailable:
      type: boolean
      notnull: true
      default: false
    is_featured:
      type: boolean
      notnull: true
      default: false
    featured_weight:
      type: integer
      notnull: true
      default: 0
    note:
      type: clob
  relations:
    Libraries:
      class: Library
      refClass: DatabaseLibrary
      local: database_id
      foreign: library_id
      foreignAlias: Databases
    Subjects:
      class: Subject
      refClass: DatabaseSubject
      local: database_id
      foreign: subject_id
      foreignAlias: Databases

DatabaseLibrary:
  columns:
    database_id: { type: integer, primary: true }
    library_id: { type: integer, primary: true }
  relations:
    Database:
      onDelete: CASCADE
    Library:
      onDelete: CASCADE

DatabaseSubject:
  columns:
    database_id: { type: integer, primary: true }
    subject_id: { type: integer, primary: true }
    featured_weight:
      type: integer
      default: -1
      primary: true
  relations:
    Database:
      onDelete: CASCADE
      foreignAlias: DatabaseSubjects
    Subject:
      onDelete: CASCADE
      foreignAlias: DatabaseSubjects

IpRange:
  tableName: ip_range
  columns:
    start_ip:
      type: string(15)
      notnull: true
    end_ip:
      type: string(15)
      notnull: true
    start_ip_sort:
      type: string(12)
      notnull: true
    end_ip_sort:
      type: string(12)
      notnull: true
    note:
      type: clob
    is_active:
      type: boolean
      notnull: true
      default: true
    is_excluded:
      type: boolean
      notnull: true
      default: false
    library_id:
      type: integer
      notnull: true
  relations:
    Library:
      onDelete: RESTRICT
      foreignAlias: IpRanges

Library:
  tableName: library
  columns:
    name:
      type: string(255)
      notnull: true
    code:
      type: string(10)
      notnull: true
      unique: true
    show_featured:
      type: boolean
      notnull: true
      default: true
    ezproxy_host:
      type: string(255)
    ezproxy_key:
      type: string(255)
    ezproxy_algorithm:
      type: string(10)
    note:
      type: clob

Subject:
  actAs:
    Sluggable:
      unique: true
      fields: [name]
      canUpdate: true
  tableName: subject
  columns:
    name:
      type: string(255)
      notnull: true

