generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Subject
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          subject
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        slug:
          help: URL designation for this subject
        weight:
          help: Sort order of options in homepage subject dropdown
      list:
        title: false
        display: [=name]
        sort: [name, asc]
        object_actions:
          _delete: ~
      filter:
        class: false
      form:
        display: [name, slug, weight, DatabaseSubject]
      edit:
        title: false
      new:     ~
