# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  stylesheets:
    - /js/jquery/css/ui-lightness/jquery-ui-1.8.17.custom.css
    - backend.css

  javascripts:
    - /js/jquery/js/jquery-1.7.1.min.js
    - /js/jquery/js/jquery-ui-1.8.17.custom.min.js
    - global.js
    - backend.js
    - /js/lib/FR.js
    - /js/lib/FR/Backend.js
    - /js/lib/FR/Backend/Sorter.js
    - /js/lib/FR/Backend/SorterRow.js

